Feature/128 create mock
reud/pj-marowd pull request #132
Opened 2020-04-01 04:41 UTC by kanade9

2020-04-01 05:03 UTC, reud requested changes

2020-04-01 05:03 UTC, reud commented on backend/functions/src/create_mock.ts
> +let randomStateForClass = 100;
@kanade9 
この辺りのパラメータ、グローバルなら何に使うのか簡単にコメントが欲しいかな！
(commentNum -> コメントの数字？これは何に使われるんだろうってなります。)

後は、変更されない値ならconstを使って欲しいです。

2020-04-01 05:03 UTC, reud commented on backend/functions/src/api.ts
> +app.get("/mock", makeMock);
@kanade9 


makeMockは型が async (batchSize: number) => voidだからapp.getに第二引数に入らないはずなんだが・・・

追: expressのコード見たけど、app.getの引数、anyなんすね・・・なぜ

予想: 

- 原因として、暗黙の型変換でbatchSizeに謎の値が入ってしまっていることが考えられます。

makeMockのメソッドの形式をasync (
  req: functions.Request,
  resp: express.Response
): Promise<void> にして見てください。 （expressのハンドラ関数は基本この形式で使われているので。）

確認：

- batchSizeは可変である必要がないので引数としては不要の認識です。固定値で良いと思います。

-　cloudfunctions側のエラーログは確認されましたか？何か出ていたらそれが解決の糸口になるかもしれません。



ブランチの形式をfeature/にしてくれたのは助かります。これにより、開発ブランチ(develop)やドキュメントブランチ（doc）と見分けがつきやすいです。

2020-04-01 05:03 UTC, reud commented on backend/functions/src/create_mock.ts
> +makeMock(33).then(r => console.log("done"));
これどのタイミングで呼ばれる認識でしょうか？

2020-04-01 14:23 UTC, kanade9 commented on backend/functions/src/api.ts
> +app.get("/mock", makeMock);
これfor分の中に100とか値ベタ書きでも同様の動きしたので型変換が原因ではないと思うんだよね。いまいちここはわからないのでissueにあげときました。cloudfunctionではエラーは返されていません！

2020-04-01 14:23 UTC, kanade9 commented on backend/functions/src/create_mock.ts
> +makeMock(33).then(r => console.log("done"));
全部終了DB書き込み完了で呼ばれる認識です

2020-04-01 14:42 UTC, reud commented on backend/functions/src/create_mock.ts
> +makeMock(33).then(r => console.log("done"));
ごめん！伝え方が悪かった。 .thenの部分じゃなくて、このmakeMock(33)が呼ばれるタイミングです。

2020-04-01 14:47 UTC, reud commented on backend/functions/src/api.ts
> +app.get("/mock", makeMock);
承知。
一旦Expressのハンドラ関数の書き方に合わせてもらえませんか？ 可能性を潰すことは重要なので。

https://expressjs.com/ja/guide/routing.html

2020-04-01 14:50 UTC, reud commented on backend/functions/src/create_mock.ts
> +makeMock(33).then(r => console.log("done"));
あまり自信はないのですが、このファイルのimport時辺りで呼ばれそうです。グローバルに置いてあるので。

2020-04-03 07:08 UTC, kanade9 commented on backend/functions/src/create_mock.ts
> +let randomStateForClass = 100;
修正しました

2020-04-03 07:15 UTC, kanade9 commented on backend/functions/src/api.ts
> +app.get("/mock", makeMock);
修正しました

2020-04-03 07:16 UTC, kanade9 commented on backend/functions/src/create_mock.ts
> +makeMock(33).then(r => console.log("done"));
修正したのでここ削除しました！

2020-04-03 07:33 UTC, reud requested changes
確認お願いします！

2020-04-03 07:33 UTC, reud commented on backend/functions/src/create_mock.ts
> +
あざます。分かりやすい

2020-04-03 07:33 UTC, reud commented on backend/functions/src/create_mock.ts
> +        await batch.commit();
今思ったけど、この辺りの処理try-catchで括ったりすれば3件しか登録出来ない理由判明するんじゃないかなって

2020-04-03 07:33 UTC, reud commented on backend/functions/src/create_mock.ts
> +        await batch.commit();
これは俺がやるならだけど,await使ってる所 1行しかないなら

```typescript
await batch.commit().catch( (e:Error) => { console.log(JSON.Stringify(e)) };
```

かなぁ・・・

2020-04-03 07:33 UTC, reud commented on backend/functions/src/create_mock.ts
> +let titleArray = ['字が大きいので見やすい。', 'すごく助かった', '言うことなしです。', '最高',
constに変更しといて！

2020-04-03 07:35 UTC, reud commented
@kanade9 
修正後、このPRにリクエストとレスポンス載せておいてもらえませんか？　ちゃんと動いている確認を取りたいです！。

2020-04-06 07:13 UTC, kanade9 commented on backend/functions/src/create_mock.ts
> +let titleArray = ['字が大きいので見やすい。', 'すごく助かった', '言うことなしです。', '最高',
OK!

2020-04-06 07:13 UTC, kanade9 commented on backend/functions/src/create_mock.ts
> +        await batch.commit();
修正しました

2020-04-06 07:48 UTC, kanade9 commented
request: 
```
curl --location --request GET 'https://us-central1-pj-marowd.cloudfunctions.net/api/mock' \
--header 'Authorization: Bearer "your-token" '
```

2020-04-06 07:48 UTC, kanade9 commented
repsonse:
OK

2020-04-06 07:50 UTC, kanade9 commented
pushとrequest,responseの確認の順番が逆になってしまいました。667ffe7でのrequest,responseがそのrequestとresponseです

2020-04-06 09:26 UTC, reud commented
@kanade9 
以下の点確認してください～！

- モックデータは想定通りに作成されているか
- ログには何も出ていないか

2020-04-07 08:29 UTC, reud commented
@kanade9 
もう一点、fakerに赤線引かれてませんでしたか？

JavaScriptのライブラリは実はそのままTypeScriptには転用できず、型定義ファイル(~.d.tsのもの)が必要となります。

大体の場合、型定義ファイルもライブラリに入っているのですが、fakerは入っていないようです。

この場合、3つの対応のどれかをする必要があります。

- 他のユーザが作った型定義ファイルを使う。
  - npm install --save @types/<module name>
  - 型定義ファイルがない場合はまずはこれを試してみてください。
  - 他のユーザが作った型定義ファイルがあればこれでTypescriptでも安全に使えるようになります。
- 自分で作る
  - ~d.tsを自分で作ります。作り方はググれば出ます。
- 違うライブラリを探す

大体この三択です。　把握しておくと良いかもしれません。


今回は型定義ファイルがあったので、インストールしておいてくれると！
[@types/faker - npm](https://www.npmjs.com/package/@types/faker)

2020-04-08 07:59 UTC, kanade9 commented
今回はエラーで怒られなかったんですけど、よく怒られる理由がやっとわかりました
Firestoreで目的のデータは作成されていて、エラー等のログはありませんでした

2020-04-08 09:02 UTC, reud approved these changes

2020-04-08 09:02 UTC, merged

2020-04-08 09:03 UTC, reud commented
LGTM マージします。