Feature/130 get avarage rating
reud/pj-marowd pull request #135
Opened 2020-04-03 06:55 UTC by kanade9

close #134 
変更箇所
swqgger修正
api/comment でtitleがnullのものを除外するように変更
api/comment でratingとratingした人の人数を授業データに送る
api/class_dataでratingとratingのモデルを作ることができるように変更
その他コードのバグ修正

2020-04-03 06:57 UTC, kanade9 commented
ratingつけた人数のカウントはrating_countedで行うのでcomment_countは消去

2020-04-03 07:26 UTC, reud requested changes

2020-04-03 07:26 UTC, reud commented on backend/functions/src/handler/api/comment.ts
> +    // firestoreではnull値を許容するのでここでnull値の設定も行う
良いコメント！

2020-04-03 07:26 UTC, reud commented on backend/functions/src/handler/api/comment.ts
> +  const classDataRecord = documentSnapshot.data();
@kanade9 エラー文読んでないので予想ですが、classDataRecord、nullの可能性があるのでeslintが怒ってるんだと思います。
ここはeslintに従って

```ts
if (!classDataRecord) {
  // classDataRecord がなかった場合のハンドリング(多分ありうるのはnot foundだから404を返して終了で良いかな。)

}
```

この様に書くべきです。

2020-04-03 07:26 UTC, reud commented on swagger.yaml
>    firebaseAuth:
@kanade9 
コード生成してください。期待通りになっているか生成コード読んで確認も出来るので。

2020-04-03 07:26 UTC, reud commented on backend/functions/src/handler/api/comment.ts
> +      const filteredData = records.filter(function(item) {
Javascriptのアロー関数を使った方がよりスマートにかけるので、可読性向上のためそうして欲しいです。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/Arrow_functions

```typescript
(item) => {return !!item.title;}
```

2020-04-03 07:26 UTC, reud commented on backend/functions/src/handler/api/comment.ts
> +  await Firestore.collection("ClassSummary")
ここのawaitもtry句の中に入れた方が良いのでは・・・？

2020-04-06 09:08 UTC, kanade9 commented on backend/functions/src/handler/api/comment.ts
> +  const classDataRecord = documentSnapshot.data();
この記法や条件分岐の方法で試してみましたが解消されませんでした。

2020-04-07 08:31 UTC, reud commented
コミット前にprettierをかけてください。

![image](https://user-images.githubusercontent.com/31179220/78647479-9cba5800-78f5-11ea-9a83-f432c3242741.png)

2020-04-07 08:35 UTC, reud commented
formerDataがundefinedの可能性があるって意味です。

![image](https://user-images.githubusercontent.com/31179220/78647826-0fc3ce80-78f6-11ea-8b59-2ae05ea879c7.png)

2020-04-07 08:43 UTC, reud commented
@kanade9 

この手順でエラー消えました。

1. `formerData.data()`を変数に代入する。
2.`変数の存在チェック(undefinedなら返す)`
3. その変数は存在していることが保証されるのでエラーが消える。

ちなみに、`!formerData.data()`で存在チェックしても`formerData.data()`が存在していることは保証されません。これは、`formerData.data()`がメソッドの呼び出しなので、`今は存在していたけど次はundefinedが変えるかもしれない`ためです。

※ここでいう存在チェックはメソッドの返り値がnullまたはundefinedではないことの確認を指します。

下記に正常に動作する書き方を載せたのでそちらを参考に編集してみてください。

![image](https://user-images.githubusercontent.com/31179220/78648183-9d9fb980-78f6-11ea-8b51-eac81a8640cc.png)

2020-04-14 10:59 UTC, kanade9 commented on backend/functions/src/handler/api/comment.ts
> +      const filteredData = records.filter(function(item) {
修正しました

2020-04-14 11:15 UTC, kanade9 commented on backend/functions/src/handler/api/comment.ts
> +  await Firestore.collection("ClassSummary")
確かに！入れました

2020-04-14 12:45 UTC, kanade9 commented
ここの説明すごくよくわかりました！ありがとう！！
https://github.com/gekko-org/pj-marowd/pull/135#issuecomment-610259050

2020-04-14 12:46 UTC, kanade9 commented
<img width="931" alt="スクリーンショット 2020-04-14 21 43 35" src="https://user-images.githubusercontent.com/47267817/79226415-4fac2800-7e99-11ea-84da-f0d8184889b7.png">
コード生成したらしたらx-nullableもちゃんと反映されてた

2020-04-14 12:46 UTC, kanade9 commented on swagger.yaml
>    firebaseAuth:
生成できました〜

2020-04-14 12:47 UTC, kanade9 commented
遅くなってすいません。再度確認お願いします

2020-04-14 19:31 UTC, reud approved these changes

2020-04-14 19:31 UTC, reud commented on backend/functions/src/handler/api/comment.ts
> +    Rating = body.rating;
if 入れずに

`const Rating = body.rating || 0`

で良さそう。

2020-04-14 19:31 UTC, reud commented on backend/functions/src/handler/api/comment.ts
> +      formerRating = formerData.rating;
ここで初めて、`const formerRating = formerData.rating || 0` でいいんじゃないかな・・・？

2020-04-15 06:39 UTC, kanade9 commented on backend/functions/src/handler/api/comment.ts
> +      formerRating = formerData.rating;
上と合わせて気づいてなかった！！修正しました

2020-04-15 06:40 UTC, kanade9 commented
動作確認完了して問題はありませんでした。
cloudfunctionsにpushしてあります

2020-04-15 07:15 UTC, merged