Kzmaro develop
reud/pj-marowd pull request #19
Opened 2019-05-25 09:38 UTC by kzmaro

お願いします

2019-05-26 03:09 UTC, reud requested changes
色々

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItem.vue
> +                {{tagLabel}}
ここの変更理由が分からないです。
集計結果なのかどうかわからない場面があるとは思えません
ユーザが画面を見て、「これ集計結果なのか投票結果なのかどっちか分からない」なんて状況が発生する可能性が分からないです。
後、既存のコンポーネントを急に変更されると、ほかのコンポーネントにも影響が出るので出来るだけ変更しないか、変更する際は必ず一報してください

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItems.vue
> +            <v-card color="#FFFFDD" class="py-2">
このように書くと実際にコンポーネントを使用する際、背景色を選べなくなるため、colorはpropsにして、親から指定できるようにしてください

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItems.vue
> +                            <app-evaluation-item @rating-selected="EventConnect" :output=out
outputはBooleanなのでoutもBooleanにすべきです。Stringにしている理由はありますか

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItems.vue
> +</style>
属性の設定１つに一行使ってほしいです。
コメントがしにくいので

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItems.vue
> +                                                 :model="evaluationItemModel" :tag-label=labels[label-1]
evaluationItemModelはどこで定義されてるのですか？

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItems.vue
> +                            <app-evaluation-item @rating-selected="EventConnect" :output=out
@rating-selected="EventConnect"ですがどの評価項目に対しても同じメソッドを発火してしまうため、評価項目ごとに発火メソッドを分けるか、 EventConnect内の動作を評価項目によって変えられるようにしてほしいです

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItems.vue
> +                default: () => []
👍

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItems.vue
> +<style scoped>
ここのstyleいらないだろうし消してよくない？

2019-05-26 03:09 UTC, reud commented on src/components/ShowCase.vue
> +                    :tag-label="'心地よさ'"
Stringを入れたい場合はv-bindを使う必要ないです。
` tag-label="心地よさ" `
の方が見やすくて良いと思います

2019-05-26 03:09 UTC, reud commented on src/components/ShowCase.vue
> +                              @rating-selected="EventTest"></app-evaluation-items>
良い例だと思う　rating-selectedにバインドするメソッドの内容を作成してほしい
クリックされたら「その評価項目のラベルと値を取得」という処理にしてくれると、入力値の受け取りが出来るようになるので

2019-05-26 03:09 UTC, reud commented on src/components/AppEvaluationItems.vue
> +    import AppEvaluationItem from "./AppEvaluationItem";
import 文は@/AppEvaluationItemの方が良いです。Pathの解決をWebpack側でやってくれるようになるのでバグが起きにくくなります

2019-05-26 03:26 UTC, kzmaro commented on src/components/AppEvaluationItem.vue
> +                {{tagLabel}}
他のコンポーネントを変更する時は気をつけます。
そこの変更理由は、「集計結果を表示する時に　「おすすめ度 集計結果,人気度 集計結果」　というように何度も「集計結果」という共通する文字列が含まれるからです。それをまとめるために変更しました。

2019-05-26 03:32 UTC, reud commented on src/components/AppEvaluationItem.vue
> +                {{tagLabel}}
` 集計結果 `って文字なくても実際にはユーザ自身で集計結果だとわかると思うので個人的には必要ないかなと思います。 
「おすすめ度」だけ書かれてても、場所によって、これが入力なのか出力なのかはわかると思います

2019-05-26 03:35 UTC, reud commented on src/components/AppEvaluationItem.vue
> +                {{tagLabel}}
"(集計結果)"がマジックストリングになってるのが気になるのと、おすすめ度 集計結果,人気度 集計結果ってなんども同じ言葉が出るのがちょっと嫌です。　その表が集計結果であることはわざわざ書いて明示する必要はないと思うのと、どうしても集計結果であることを書きたいなら、
表外に書いた方がしつこくなくていいと思います

2019-05-26 03:39 UTC, kzmaro commented on src/components/AppEvaluationItem.vue
> +                {{tagLabel}}
消しますね

2019-05-26 03:55 UTC, kzmaro commented on src/components/AppEvaluationItems.vue
> +            <v-card color="#FFFFDD" class="py-2">
修正しました

2019-05-26 04:00 UTC, kzmaro commented on src/components/ShowCase.vue
> +                    :tag-label="'心地よさ'"
⭕️

2019-05-26 04:03 UTC, kzmaro commented on src/components/AppEvaluationItems.vue
> +<style scoped>
消したよ

2019-05-26 04:06 UTC, kzmaro commented on src/components/AppEvaluationItems.vue
> +    import AppEvaluationItem from "./AppEvaluationItem";
d(^_^o)

2019-05-26 04:09 UTC, kzmaro commented on src/components/AppEvaluationItems.vue
> +                                                 :model="evaluationItemModel" :tag-label=labels[label-1]
あ、いりませんでした

2019-05-26 04:17 UTC, reud commented on src/components/AppEvaluationItems.vue
> +                                                 :model="evaluationItemModel" :tag-label=labels[label-1]
いえ、modelは入力時は必要です。入力した値はmodelに格納されるので

2019-05-26 04:19 UTC, kzmaro commented on src/components/ShowCase.vue
> +                              @rating-selected="EventTest"></app-evaluation-items>
修正しました

2019-05-26 04:20 UTC, kzmaro commented on src/components/AppEvaluationItems.vue
> +                            <app-evaluation-item @rating-selected="EventConnect" :output=out
booleanに直しました。
評価項目ごとに分けるという動作がいまいちよくわかりません。

2019-05-26 04:21 UTC, kzmaro commented on src/components/AppEvaluationItems.vue
> +                            <app-evaluation-item @rating-selected="EventConnect" :output=out
EvaluationItemsはEvaluationItemをまとめたコンポーネントなので、入力された値をそのままわたすという仕組みではダメなのですか？

2019-05-26 04:22 UTC, kzmaro commented on src/components/AppEvaluationItems.vue
> +                            <app-evaluation-item @rating-selected="EventConnect" :output=out
メソッドを分ける意味を教えてください

2019-05-26 05:41 UTC, reud commented on src/components/AppEvaluationItems.vue
> +                            <app-evaluation-item @rating-selected="EventConnect" :output=out
入力時の話です。入力値を取得するのに必要です。メソッドを分けるか、keyによって動作を変えたりしないと、どのEvaluationItemになんの値が入ってるかを取得できないと思います(出来るならそれでいいです)

2019-05-26 05:41 UTC, reud commented on src/components/ShowCase.vue
> +                              @rating-selected="EventTest"></app-evaluation-items>
確認します

2019-05-26 05:43 UTC, reud commented on src/components/ShowCase.vue
> +                              @rating-selected="EventTest"></app-evaluation-items>
pushされてないので後々確認します

2019-05-30 00:52 UTC, reud submitted a review, later dismissed
凄く良いです！！！

2019-05-30 00:52 UTC, reud commented on src/components/AppEvaluationItem.vue
> +                {{tagLabel}}
これ好き　インデントは大事

2019-05-30 00:52 UTC, reud commented on src/components/AppEvaluationItem.vue
>              }
オッケオッケー　変更が必要な訳を理解した！
良い実装！ナイス！

2019-05-30 00:52 UTC, reud commented on src/components/AppEvaluationItems.vue
> +                            <app-evaluation-item :model="model" @rating-selected="EventConnect" :output=out
わざわざ再コミットさせるのもアレだからいらないけど、属性のバインドは一行に一個にしてくれるとコメントが楽です〜
例えば
```
<app-evaluation-item :model="model" @rating-selected="EventConnect" :output=out
```
は
```
<app-evaluation-item 
:model="model"
 @rating-selected="EventConnect"
 :output=out
```
って感じ(インデントは良い感じに)

2019-05-30 00:52 UTC, reud commented on src/components/ShowCase.vue
> +            EventTest2: function (val, label) {
👍 👍

2019-05-30 02:11 UTC, kanade9 reviewed
修正ありがとうございます！！

2019-05-30 02:11 UTC, kzmaro commented on src/components/ShowCase.vue
> +                @click="EventTest">
一行に一つのバインド、オッケーです！

2019-05-30 02:14 UTC, merged