Dev/edit comment
reud/pj-marowd pull request #39
Opened 2019-07-10 14:27 UTC by kanade3

ここのレスポンシブがどうしても出来ません

2019-07-11 03:52 UTC, reud requested changes
多分うまく行かない原因わかった

2019-07-11 03:52 UTC, reud commented on src/components/pages/EditComment.vue
> +                    label="コメント"
![image](https://user-images.githubusercontent.com/31179220/61020647-65a42e00-a3d9-11e9-9dac-f00b9f250aac.png)
上にも枠線付けられたりってできます？

2019-07-11 03:52 UTC, reud commented on src/components/pages/ListPage.vue
> +                    ></AppClassSummary>
悩んでたんだろうけどここの実装の意味がわからないです v-layoutで一行、二つあるので二行って感じですかね？
一行に入るClassSummaryの数はグリッドレイアウトで決まるので、v-layoutで分ける必要はないと思います

v-layoutどっちか消してみて欲しいです

あと、xsとmdの間に一段階あるとより見栄えが良くなりそうです！ポイントは4で

2019-07-11 03:52 UTC, reud commented on src/components/pages/ListPage.vue
> +            <v-layout row-wrap>
正しくは row wrap です「ハイフンで繋がずに半角スペースで分けてみてください」
https://qiita.com/Issyo_Vo/items/a1771195bf65514d2814

2019-07-11 04:07 UTC, kanade3 commented on src/components/pages/EditComment.vue
> +                    label="コメント"
そこは気づいてて、filledとかautlinedの設定しても変化がないのでvuetify側の原因かと

2019-07-11 08:08 UTC, reud commented on src/components/pages/EditComment.vue
> +                    label="コメント"
料理！じゃあキープで大丈夫！

2019-07-11 11:12 UTC, reud commented on src/components/pages/EditComment.vue
> +                    label="コメント"
了解の間違いでした
プレースホルダーとかっておけます？？？
無い方がいいと思ったらそれでおkです！

2019-07-11 12:11 UTC, kanade3 commented on src/components/pages/EditComment.vue
> +                    label="コメント"
プレースホルダ？そこに何か置く予定とかありましたっけ？？

2019-07-15 14:38 UTC, kanade9 commented on src/components/pages/ListPage.vue
> +                    ></AppClassSummary>
修正しました！！sm4では見栄えが悪かったのでsm6に修正しました

2019-07-15 14:39 UTC, kanade9 commented on src/components/pages/ListPage.vue
> +            <v-layout row-wrap>
治りました〜〜〜〜ありがとう〜〜😄😄

2019-07-15 15:29 UTC, reud commented
大丈夫そうなのでマージしますね
どうもです〜！

2019-07-15 15:32 UTC, reud reviewed
あざす！

2019-07-15 15:32 UTC, reud approved these changes
お疲れ様です

2019-07-15 15:33 UTC, merged