swagger追加
reud/pj-marowd pull request #77
Opened 2019-09-01 11:56 UTC by kanade9

[WIP] ファイル作りました

2019-09-02 00:55 UTC, reud commented
PRのタイトル先頭にWIP: をつけて欲しいです

2019-09-02 00:55 UTC, reud commented
これは一回PRをOpenすると出来ないので次回からで構いませんが、Draft でPull Requestを作って欲しいです。　これは他のPRを参考にしてください

2019-09-02 00:56 UTC, reud commented
![image](https://user-images.githubusercontent.com/31179220/64084582-dd526180-cd67-11e9-892f-49377672b049.png)
こんな感じになると

2019-09-02 00:57 UTC, reud commented
node_modulesは共有すべきでないフォルダのため、.gitignoreで弾いて欲しいです

2019-09-02 01:08 UTC, reud reviewed
思ったところコメントしました　作ってなさそうな部分は飛ばしています。

2019-09-02 01:08 UTC, reud commented on backend/pj-functions/.gitignore
> +.env
バックエンドの下にあるnode_modules,多分使ってないと思うので削除して欲しい

2019-09-02 01:08 UTC, reud commented on backend/yarn.lock
> +
ここも使ってないと思う 実際に開発に使用しているディレクトリは backend/pj-functionsの下っぽいので

2019-09-02 01:08 UTC, reud commented on swagger.yaml
> +  /get_comment:
get_commentはGETリクエストで送るって書くと、二重の意味になって冗長のため ここのパスは `/comment` が良いと思う！

2019-09-02 01:08 UTC, reud commented on swagger.yaml
> +      - name: "授業の名前"
nameは英語になるかな　例えばパラメータとしてuidを指定しているけど、name部分が `/hoge?uid=~~` みたいなパスパラメータになるので

2019-09-02 01:08 UTC, reud commented on swagger.yaml
> +          description: "授業がDBの中にない場合"
404の方がいいかな

2019-09-02 01:08 UTC, reud commented on swagger.yaml
> +  /get_class:
ここも

2019-09-02 01:08 UTC, reud commented on swagger.yaml
> +        400:
同様

2019-09-02 01:08 UTC, reud commented on swagger.yaml
> +      - name: "授業の名前"
同様

2019-09-15 16:46 UTC, reud requested changes
編集ありがとう！

パスパラメータは中々良い設定が分かりにくいので僕も他のサービスを参考にしてます。
後HTTPメソッドは下記が参考になるかも
https://qiita.com/r_fukuma/items/a9e8d18467fe3e04068e

2019-09-15 16:46 UTC, reud commented on .gitignore
> +
あざ！

2019-09-15 16:46 UTC, reud commented on frontend/.gitignore
> +.node_modules
ここ.必要？普通に`node_modules`っていうフォルダ名だと思うんだけど・・・

2019-09-15 16:46 UTC, reud commented on swagger.yaml
> +      - name: "class_name"
`/class?class_name=` は少し冗長なので普通に`/class?name=`の方が良いと思うけど, どう？

2019-09-15 16:46 UTC, reud commented on swagger.yaml
> +        404:
500系の方が良いかな 多分内部エラーが考えられるので

2019-09-15 16:46 UTC, reud commented on swagger.yaml
>    /delete_comment:
HTTPのMETHODに"DELETE"っていうのがあるので'POST"を"DELETE"にしてエンドポイントを`/comment`にしたい！

2019-09-15 16:46 UTC, reud commented on swagger.yaml
>    /post_class:
`class` だけで大丈夫！

2019-09-15 16:46 UTC, reud commented on swagger.yaml
>    /post_comment:
ここもメソッド名をエンドポイントにつける必要はないと思うよ！ 全部`/comment`に統一して、送られてきたメソッドによって動作変えられるよ！

2019-09-15 16:50 UTC, reud commented on swagger.yaml
> +      - name: "class_name"
/commentだったね　ごめんなさい。　そのままで！

2019-09-15 16:54 UTC, reud reviewed
絨毯爆撃でコメントしました

2019-09-15 16:54 UTC, reud commented on swagger.yaml
> +          description: "ユーザのuid。コメント編集を許可するかどうかに利用"
これちょっと迷います。uidをクエリに載せるとURLにバーンって個人情報の塊が・・・

2019-09-15 16:54 UTC, reud commented on swagger.yaml
> +
ありがとう！！！　この辺

2019-09-16 01:21 UTC, kanade9 commented on frontend/.gitignore
> +.node_modules
?ここにもgitignoreが存在することを今知った

2019-09-16 01:21 UTC, kanade9 commented on swagger.yaml
> +        404:
おけです

2019-09-16 01:59 UTC, reud commented on frontend/.gitignore
> +.node_modules
草

2019-09-16 02:25 UTC, kanade9 commented on frontend/.gitignore
> +.node_modules
一番上の階層のgitignoreでfrontendのnoded_modules弾いたけどそれでいいよね？？

2019-09-16 02:25 UTC, kanade9 commented on swagger.yaml
>    /post_comment:
理解した！！

2019-09-16 02:25 UTC, kanade9 commented
修正しましたー

2019-09-16 02:36 UTC, reud reviewed
概ね大丈夫です！ あざす！POSTとPUTだけ何送ればいいか書いて無くない？

2019-09-16 02:36 UTC, reud commented on swagger.yaml
> +    post:
post,putのパラメータis 何 これだと何送ればいいか分からなくない？

2019-09-16 02:36 UTC, reud commented on swagger.yaml
> +    put:
putとpostのパラメータ is 何

2019-09-17 06:41 UTC, kanade9 commented
直しました

2019-09-17 07:51 UTC, reud submitted a review, later dismissed

2019-09-17 07:51 UTC, reud commented on swagger.yaml
> +          type: "integer"
あざす

2019-09-17 07:51 UTC, reud commented on swagger.yaml
> +          description: ""
直します

2019-09-17 07:51 UTC, reud commented on swagger.yaml
>        description: ""
ここも書いて欲しかった

2019-09-17 07:51 UTC, reud commented on swagger.yaml
> +          description: "An error occur"
error occuredの方が自然かも

2019-09-20 00:09 UTC, reud commented
Models初めて見たので、swagger editorで動作確認したんですけど
こんな感じになっちゃいました。　そちらの環境だとうまく行ったりしますか？
![image](https://user-images.githubusercontent.com/31179220/65289589-47e80780-db86-11e9-94f5-f2d8de0ce42d.png)

2019-09-20 00:28 UTC, kanade9 commented
parameterの方ではうまく表示されるんですけどモデルのほうではうまく表示されないです

2019-09-21 13:35 UTC, reud commented
よくわからないんだけど、0,1,2ってなんの意図？
ここ何書こうとしているのかいまいちわからなくて反応できない・・・

2019-09-21 13:36 UTC, reud commented
type: objectでexampleにschemaを入れてるのも分からない・・・　

2019-09-21 15:40 UTC, kanade9 commented
0,1,2はコメントの順に取得していくっていう意図だったんだけどわかりにくいんで消しました
modelのところは修正して、こっち側では正しく表示されました。例を入れているとうまく表示されないことがわかったので例のところはコメントアウトして外してます。

2019-09-22 23:59 UTC, reud commented on swagger.yaml
> +           $ref: '#/definitions/comment'
ここ　definitions(型定義のイメージ)なので
```
  comments:
    type: "object"

    properties:
      comment_example01:
        type: "array"
        items:
           $ref: '#/definitions/comment'
```
は変や

{ "comments": {
  "comment_example01" : comment[]
}}
ってjsonになるよ

2019-09-22 23:59 UTC, reud commented on swagger.yaml
> +           $ref: '#/definitions/comment'
```
  comments:
        type: "array"
        items:
           $ref: '#/definitions/comment'
```
なんとなくこんな感じの認識だけど何か懸念あります？

2019-09-23 02:20 UTC, kanade9 commented on swagger.yaml
> +           $ref: '#/definitions/comment'
ないです　修正します！

2019-09-24 03:17 UTC, reud approved these changes

2019-09-24 03:17 UTC, merged