バックエンド関数作成途中
reud/pj-marowd pull request #80
Opened 2019-11-17 01:12 UTC by kanade9

2019-11-17 01:45 UTC, reud requested changes

2019-11-17 01:45 UTC, reud commented on backend/functions/src/index.ts
> +export const comments = functions.https.onRequest((request, response) => {
- PR時に`(request, response) => {}` な関数はrequest.tsみたいな所にファイルを切り分けてまとめた方が見やすいかも、index.tsでは `export const comments = request.GetComments` みたいなイメージになります。

後、.thenでなく、async/awaitの方式を理解すればかなりサクサク書ける様になると思うので試してみてください！

- [Promiseの使い方、それに代わるasync/awaitの使い方 - Qiita](https://qiita.com/suin/items/97041d3e0691c12f4974)
- [async await の使い方 - Qiita](https://qiita.com/niusounds/items/37c1f9b021b62194e077)

2019-11-17 14:12 UTC, kanade9 commented
136行目〜のforループで取得してとってきたdataを順に追加してjsonで返すやり方についてもアドバイスが欲しいです

2019-11-17 14:13 UTC, kanade9 commented on backend/functions/src/index.ts
> +export const comments = functions.https.onRequest((request, response) => {
astncとawait試してみます

2019-11-19 02:23 UTC, reud commented
slackにてお伝えしました

2019-11-26 19:07 UTC, reud commented
`firebase deploy --only functions:sample ` みたいに一個だけデプロイとかできるみたいっすね

2019-11-26 19:39 UTC, reud commented on backend/functions/src/index.ts
> +async function sampleRequest(req:functions.Request,resp:express.Response) {
sampleの関数を書いてみました。確認お願いします

2019-12-18 06:47 UTC, reud commented
GET /commentsについてですが、クエリ無い場合のハンドリングもお願いしたいです〜

2019-12-18 08:17 UTC, reud commented
GET /comments PASSED!

2019-12-18 08:29 UTC, reud commented
GET /comment PASSED!

2019-12-24 02:25 UTC, kanade9 commented
授業データの追加[POST] class_dataを追加しました！
DBに格納する情報にnameとfavamountが抜けてたことに今気づいたのでswaggerも修正しました
確認お願いします

2019-12-27 05:54 UTC, kanade9 commented
実装終了しました！実装にあたってパラメータを変更した部分(commentに授業名のname)などを追加したり等変更した部分があるのでそちらも確認お願いします！

2019-12-27 09:40 UTC, reud commented
# 現在発生している問題やTODO
## 時間形式のフォーマットが違う
ここにアクセスするとupdate atとcreated atのformat が異なる
https://us-central1-pj-marowd.cloudfunctions.net/comments?class_name=dummy%20class
## swagger.yamlのGET /commentの内容の修正
comment_id を uidにして欲しい

@kanade9 お願いします！！

2020-01-08 07:43 UTC, reud reviewed
あzms

2020-01-08 07:43 UTC, reud commented on backend/functions/src/index.ts
> +    class_created_time = doc.data().created_at;
これ確か授業情報が入っていた場合ってどうするんだっけ・・・　
後、変数名がclass_d だけど少しわかりにくいかも・・・ d is 何ってなる。
後、今更だけど変数名はcamelCaseで・・・
[StyleGuide - TypeScript Deep Dive 日本語版](https://typescript-jp.gitbook.io/deep-dive/styleguide#%E5%A4%89%E6%95%B0%E3%81%A8%E9%96%A2%E6%95%B0)

この関数は、新規授業の作成のハンドラの認識だけど合ってる？
もし合ってるなら、すでに授業がある場合は何もしない（４０９を返す）
でも良いかなって思ってるけどどう？

参考：
[rest - HTTP response code for POST when resource already exists - Stack Overflow](https://stackoverflow.com/questions/3825990/http-response-code-for-post-when-resource-already-exists)

2020-01-08 07:43 UTC, reud commented on backend/functions/src/index.ts
>      // 'comment_id': body.comment_id, commentID無くした
ここのコメント消して欲しい！

2020-01-08 07:47 UTC, kanade9 commented on backend/functions/src/index.ts
> +    class_created_time = doc.data().created_at;
変数名は直します。
新規授業作成の場合も、更新の場合もどっちでも使えるように(PUTメソッドを使わないので)この関数を作った。

2020-01-08 07:48 UTC, kanade9 commented on backend/functions/src/index.ts
>      // 'comment_id': body.comment_id, commentID無くした
👍

2020-01-08 07:50 UTC, reud commented on backend/functions/src/index.ts
> +    class_created_time = doc.data().created_at;
@kanade9 ごめん完全忘れているんだけど、PUT(もしくはPATCH)実装しない理由とかってあったっけ・・・？
ないならメソッドで分けた方が良いんじゃないかなと思います

2020-01-08 07:52 UTC, reud commented on backend/functions/src/index.ts
> +    class_created_time = doc.data().created_at;
理解

2020-01-08 07:53 UTC, kanade9 commented on backend/functions/src/index.ts
> +    class_created_time = doc.data().created_at;
PUTメソッドは無くして、POSTメソッドで新規作成と更新を行なっているので(前slackで送ったものです)ここにまとめました

2020-01-08 08:37 UTC, kanade9 commented
エラー解消したのでマージします

2020-01-08 08:38 UTC, kanade9 commented on swagger.yaml
> +
修正しました

2020-01-08 08:40 UTC, reud commented
お疲れ様です！

2020-01-08 08:40 UTC, reud approved these changes

2020-01-08 08:40 UTC, merged