Backend processing
reud/pj-marowd pull request #83
Opened 2020-01-31 14:57 UTC by kanade9

backend ミドルウェアで認証成功時のみ処理をするようにしました

2020-02-02 04:35 UTC, reud requested changes
確認お願いします〜

2020-02-02 04:35 UTC, reud commented on backend/functions/src/index.ts
> +  // @ts-ignore
@kanade9 
ts-ignoreする時は理由も書いてくれると助かる！　エラーを握り潰している状態なので握り潰した原因は書いた方が良いと思う！

2020-02-02 04:35 UTC, reud commented on backend/functions/src/index.ts
> +const Verification = function(req: functions.Request, resp: express.Response, next: () => void) {
@kanade9 
可読性の問題だけど、 `.then` を使わずに.thenを使う場所があるなら`async func`で書いて欲しい！

2020-02-02 04:35 UTC, reud commented on backend/functions/src/index.ts
> +  const tokenval = req.headers.authorization.toString().slice(7);
@kanade9 
ここ、7ってマジックナンバーは言っているけどなんの数字か上のコメント入れてくれると助かる！
val(値)じゃなくてstr(文字列)の方が情報多くて良いかも

2020-02-02 04:35 UTC, reud commented on backend/functions/src/index.ts
> +commentData.use(Verification);
@kanade9 
まとまってて良いね

2020-02-02 04:35 UTC, reud commented on backend/functions/src/index.ts
> +    if (record==undefined){
@kanade9 
ここ、 `if(!record)` の方が良いかも、undefinedって明示的に書かなくても前にびっくりつけると存在するかどうかの判定がboolで返るよ！

2020-02-02 04:35 UTC, reud commented on backend/functions/src/index.ts
> +    resp.send('token error');
出来るならで良いけど、401 Unauthorized返した方が自然だと思う

2020-02-03 08:06 UTC, kanade9 commented on backend/functions/src/index.ts
> +  // @ts-ignore
async awaitで書いたのでts-ignore解消しました！

2020-02-03 08:07 UTC, kanade9 commented on backend/functions/src/index.ts
> +const Verification = function(req: functions.Request, resp: express.Response, next: () => void) {
直しました！！

2020-02-03 08:08 UTC, kanade9 commented on backend/functions/src/index.ts
> +  const tokenval = req.headers.authorization.toString().slice(7);
👍👍

2020-02-03 08:11 UTC, kanade9 commented on backend/functions/src/index.ts
> +    resp.send('token error');
おけです

2020-02-03 08:11 UTC, kanade9 commented on backend/functions/src/index.ts
> +    if (record==undefined){
スッキリしました！

2020-02-03 09:22 UTC, reud commented on backend/functions/src/index.ts
> +  // @ts-ignore
@kanade9 
> ts-ignore解消しました！

コメント消しておいて欲しいです！

2020-02-03 09:22 UTC, reud commented on backend/functions/src/index.ts
> +
@kanade9 

ここ、もう少しわかりやすく書いて欲しい！
コード読む人は

> 不要な文字列

ここで、なぜ不要なのか、なぜ不要な部分が入っているのか疑問に思うよ！
あとは、何故7なのか迷った

俺も10分ぐらいかけて、`Bearer `の部分だと気づいた。
僕がコメント書くなら

// Authorizationヘッダーは`Bearer <id_token>`の形式のため、id_tokenを取り出すために7文字目以降の文字列を切り出している

になるかな

2020-02-03 09:22 UTC, reud commented on backend/functions/src/index.ts
> +    resp.send('token error');
@kanade9 
ここ無理そう？厳しかったらResolveしちゃうので教えてください

2020-02-03 09:23 UTC, reud reviewed
返した！

2020-02-03 09:28 UTC, kanade9 commented on backend/functions/src/index.ts
> +    resp.send('token error');
もう一度修正しました

2020-02-04 11:57 UTC, reud approved these changes

2020-02-04 11:57 UTC, merged